### ISSUE TITLE
someone on bsky reported an exception

### ISSUE THREAD

**Issue by ianklatzco** [mshxd/bskyfollowbotblock#3]
https://staging.bsky.app/profile/rainerfloo.bsky.social/post/3jvhbyjnjw72n
![image](https://github.com/mshxd/bskyfollowbotblock/assets/1487413/e698fb1a-8ba3-439c-bef7-4628b3dd3cba)

**Comment by mshxd** [comment]
Checked the logs, looks like an invalid username. Need to either add validation to the field or display some text indicating to use your full handle.
